### ISSUE TITLE
How to deal appropriately with species for which multiple genomes/annotations exist

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/legfed_gene_families#11]
Chickpea desi should be added to the trees to avoid usability issues regarding desi genes.

**Comment by adf-ncgr** [comment]
The current thinking as I understand it (@scannon correct me if I'm wrong or this deserves further elaboration) is that within-species allelic diversity (segregating and subject to recombination) is different in kind from between-species differences that are presumably "fixed". Also, adding every gene we have for a species would create some usability issues when it comes to lucky species like medtr that already have > 10 genomes. 

That said, there are probably conversations to be had about how to handle cases of presence absence variation (some of which might be due to artifacts in assemblies/annotations), and how to harness our dynamic tree-building powers to make this all a "fewer seams" experience for our users. See this issue for some embryonic thoughts on the subject: 
LegumeFederation/Interface-and-Usability#5

@jd-campbell showed some interest in this subject too, so pulling her onto the thread

**Comment by sammyjava** [comment]
Why choose kabuli over desi for tree representation for chickpea?

**Comment by adf-ncgr** [comment]
I think this was a case of first-come, first-served; there may be some difference in quality between the two as well, but I don't think that was the driver.

**Comment by sammyjava** [comment]
Well, I'd certainly like a policy of "if the genome is in LIS, it's in the trees." Otherwise users hit roadblocks when going from tool to tool. On a higher level, "all genomes in LIS are equally supported by all the tools." If the data exists, of course (a tissue expression atlas, for example, may not).

**Comment by adf-ncgr** [comment]
I'd like a clearly defined policy too, though I may not subscribe to yours.

**Comment by StevenCannon-USDA** [comment]
My sense has been that the assembly and annotation quality are better for kabuli than desi.

One suggestive measure: pseudomolecule assembly lengths:
Desi  ICC4958.v2       333,999,488
Kabuli  CDC Frontier    347,247,377
  Desi pseudomolecules are 4% longer

Also, look at the synteny fragmentation for the two chickpeas vs. Medicago, e.g.
https://legumeinfo.org/gb2/gbrowse/Mt4.0/?start=1;stop=52991155;ref=Mt1;width=1024;version=100;flip=0;grid=1;id=7fe311a3dfe45761aa416519f0fbd999;l=synteny_blocks_with_cicer%1Esynteny_with_cicer_arietinum_2_0#<https://legumeinfo.org/gb2/gbrowse/Mt4.0/?start=1;stop=52991155;ref=Mt1;width=1024;version=100;flip=0;grid=1;id=7fe311a3dfe45761aa416519f0fbd999;l=synteny_blocks_with_cicer%1Esynteny_with_cicer_arietinum_2_0>

**Comment by jd-campbell** [comment]
But the gene models between desi and kabuli are similar, yes? So why not have the links to the desi genes in the kabuli pop up box on the gene family tree?

=========================
Jacqueline D. Campbell (Farrell), PhD
Iowa State University
jdjax@iastate.edu
##Sent from my iPhone
##Please excuse any spelling or grammar errors.
________________________________

**Comment by StevenCannon-USDA** [comment]
Revisit in future. Need to handle the situation in general: what to do when there are many accessions for a species?
